### ISSUE TITLE
Feature Request: search by "Nickname" field

### ISSUE THREAD

**Issue by rich86** [kopischke/alfred-pushdial#4]
Hi,

It'd be really great if it were possible to search by nickname field, i.e.: "call mum" or "dial mum" in the same way that Siri makes use of the field on the iPhone.

I'm not sure if this is something that'd be possible with the contacts/numbers script currently used?

I've had a look through the script, but I'm not confident enough to attempt to add this myself, so I'm raising this ticket.

Thanks,
Richard

**Comment by kopischke** [comment]
This should be doable – _contacts_ supports nicknames, I’ll just have to clean up the presentation code a bit.

**Comment by kopischke** [comment]
Added in release 1.1.0
